# Generated by Django 4.2.5 on 2023-09-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.FileField(null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=90, null=True)),
                ('come_data', models.DateField(auto_now_add=True)),
                ('valid_date', models.DateField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('from_bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruducts.bolim')),
            ],
        ),
    ]
